languageCode = "en-US"
defaultContentLanguage = "en"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  # Git hub repo link
  editURL = ""
  description = "The cloud journey 100 Days"
  author = "daotq2k@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
[Languages.en]
title = "Learn SEO from basics to advanced"
weight = 1
languageName = "English"

canonifyURLs = true 

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = 1